# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-12 02:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VipCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.CharField(default='', max_length=20, verbose_name='\u5361\u53f7')),
                ('name', models.CharField(default='', max_length=50, verbose_name='\u59d3\u540d')),
                ('tel', models.CharField(default='', max_length=11, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('integral', models.IntegerField(default=0, verbose_name='\u79ef\u5206')),
                ('money', models.IntegerField(default=0, verbose_name='\u50a8\u503c\u4f59\u989d')),
                ('gender', models.CharField(choices=[('male', '\u7537'), ('female', '\u5973')], default='female', max_length=7, verbose_name='\u6027\u522b')),
                ('address', models.CharField(default='', max_length=200, verbose_name='\u5bb6\u5ead\u5730\u5740')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='\u751f\u65e5')),
                ('weixin', models.CharField(blank=True, max_length=20, null=True, verbose_name='\u5fae\u4fe1\u53f7')),
                ('des', models.CharField(blank=True, max_length=200, null=True, verbose_name='\u63cf\u8ff0')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4f1a\u5458\u5361',
                'verbose_name_plural': '\u4f1a\u5458\u5361',
            },
        ),
    ]
