# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-13 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vipcard',
            name='openid',
            field=models.CharField(default='', max_length=50, verbose_name='\u5fae\u4fe1ID'),
        ),
    ]
