# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcard', '0002_vipcard_openid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcard',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='\u5bb6\u5ead\u5730\u5740'),
        ),
        migrations.AlterField(
            model_name='vipcard',
            name='openid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u5fae\u4fe1ID'),
        ),
        migrations.AlterField(
            model_name='vipcard',
            name='tel',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u624b\u673a\u53f7\u7801'),
        ),
    ]
