# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-25 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vipcard', '0003_auto_20170725_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vipcard',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u59d3\u540d'),
        ),
    ]
